name: "PR Title Checker"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - 'main'

permissions:
  pull-requests: write

jobs:
  pr_title_checker:
    runs-on: ubuntu-slim
    steps:
      - name: Check PR title
        id: lint_pr_title
        continue-on-error: true
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            perf
            test
            chore
            refactor

      - name: Comment on PR
        if: ${{ always() && steps.lint_pr_title.outputs.error_message != null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          message: |
            The title of your PR is non-compliant to the conventions.

            ${{ steps.lint_pr_title.outputs.error_message }}

            Please refer to our [GitHub documentation in Notion](https://www.notion.so/roclub/Git-GitHub-GitFlow-85cbb825be004d4d8b8ff6c0fa12204b?pvs=4#47e4e0bd334a4b0da3f6f3ad33e4009a).

      - name: Delete previous PR comment
        if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true

      - name: Fail build
        if: ${{ steps.lint_pr_title.outcome == 'failure' }}
        run: |
          echo "PR title validation failed."
          echo
          echo "${{ steps.lint_pr_title.outputs.error_message }}"
          echo
          echo "Please refer to our GitHub documentation in Notion:"
          echo "https://www.notion.so/roclub/Git-GitHub-GitFlow-85cbb825be004d4d8b8ff6c0fa12204b?pvs=4#47e4e0bd334a4b0da3f6f3ad33e4009a"
          exit 1
